<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title> MABE</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="css/metisMenu.min.css" rel="stylesheet">

    <!-- DataTables CSS -->
    <link href="css/dataTables.bootstrap.css" rel="stylesheet">
	
	<!-- DataTables Responsive CSS -->
    <link href="css/dataTables.responsive.css" rel="stylesheet">
	
	<!-- Custom CSS -->
	<link href="css/admin.css" rel="stylesheet">
	
	<!-- CSS Bus -->
    <link href="css/ventas.css" rel="stylesheet">

    <!-- Timeline CSS -->
    <link href="css/timeline.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="css/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
	<link href="css/stylish-portfolio.css" rel="stylesheet">
    <link href="css/font-awesome.min.css" rel="stylesheet" type="text/css">
	
	<!-- Include the plugin's CSS and JS: -->
	<script type="text/javascript" src="js/bootstrap-multiselect.js"></script>
	<link rel="stylesheet" href="css/bootstrap-multiselect.css" type="text/css"/>

    
</head>

<body>
	<div class="row color2">
		<div class="container">
            
                <div class="col-xs-12 col-sm-6 col-md-8 col-lg-8 centrar1">	
						<a style="color:white; text-decoration:none; font-size:40px; font-family:Algerian" href="index.php" >
							<img src="img/logo.png" alt="" width="150px" height="52px">
						</a>	
                </div>
                <div class="hidden-xs col-sm-6 col-md-4 col-lg-4 centrar1">
                        <a href="#"><img src="img/facebook.png" alt="" width="32px" height="32px"></a>
                        <a href="#"><img src="img/google.png" alt="" width="32px" height="32px"></a>
                        <a href="#"><img src="img/twitter.png" alt="" width="32px" height="32px"></a>
                </div>
            </div>
    </div><br>
		