									<div class="input-group">
										<span class="input-group-addon" ><img src="img/app.png" width=20 height=20></span>
										<input type="text" class="form-control" placeholder="Apellido Paterno" id="app" name="app" required >
									</div>
									<div class="input-group">
										<span class="input-group-addon"><img src="img/apm.png" width=20 height=20></span>
										<input type="text" class="form-control" placeholder="Apellido Materno" id="apm" name="apm" required >
									</div>
									<div class="input-group">
										<span class="input-group-addon"><img src="img/bebe.png" width=20 height=20></span>
										<input type="text" class="form-control" placeholder="Nombres" id="nom" name="nom" required >
									</div>
									<div class="input-group">
										<span class="input-group-addon"><img src="img/ci.png" width=20 height=20></span>
										<input type="text" class="form-control" placeholder="Carnet de Identidad" name="ci" id="ci" pattern="[0-9]+.{6,}" required
										title="Ingrese solo numeros minimo 6 caracteres">
									</div>
									<div class="input-group">
										<span class="input-group-addon"><img src="img/calendar.png" width=20 height=20></span>
										<input type="text" class="form-control" placeholder="Año Nacimiento" name="edad" id="edad" required>
									</div>
									<div class="input-group">
										<span class="input-group-addon"><img src="img/genero.png" width=20 height=20></span>
										<select class="form-control" name='sexo' id="sexo" required>
												<option value="">Sexo</option>
												<option value='Masculino'>Masculino</option>
												<option value='Femenino'>Femenino</option>
										</select>
									</div>
									<div class="input-group">
										<span class="input-group-addon"><img src="img/mail.png" width=20 height=20></span>
										<input type="email" class="form-control" placeholder="Correo Electronico" id="mail" name="mail" required>
									</div>
									<div class="input-group">
										<span class="input-group-addon"><img src="img/telf.png" width=20 height=20></span>
										<input type="text" class="form-control" placeholder="Telefono" id="tel" name="tel" pattern="[0-9]+.{7,}" required
										title="Ingrese solo numeros minimo 7 caracteres">
									</div>
									<div class="input-group">
										<span class="input-group-addon"><img src="img/dir.png" width=20 height=20></span>
										<input type="text" class="form-control" placeholder="Direccion" id="dir" name="dir"required>
									</div>
									<div class="input-group">
										<span class="input-group-addon"><img src="img/foto.png" width=20 height=20></span>
										<input type='file' name='archivo' required id="foto" class="form-control"/>
									</div>
									</br>