	
		<section class="color2">
            <br><br><br><br>
        </section>
	<div class="container">
        <footer class="color4">
            <br>
				<p>Derechos reservados @2015 <a>Andreus</a></p>
			</br>
			
        </footer>
        <script>window.jQuery || document.write('<script src="js/jquery-1.10.1.min.js"><\/script>')</script>
		<script src="js/bootstrap.js"></script>
		<script src="js/bootstrap-datepicker.js"></script>
		<script>
			$(document).ready(function () {
				$('.carousel').carousel({
					interval: 3000
				});
			});
		</script>
	</div>	
    </body>
</html>