    <div class="container">    
		<section class="color2">
                <div class="row">
                    
                </div><br>
        </section>
		
		<!-- jQuery -->
		<script src="js/jquery.min.js"></script>

		<!-- Bootstrap Core JavaScript -->
		<script src="js/bootstrap.min.js"></script>
		
		<!-- DataTables JavaScript -->
    	<script src="js/jquery.dataTables.min.js"></script>
		<script src="js/dataTables.bootstrap.min.js"></script>
		
		<!-- Page-Level Demo Scripts - Tables - Use for reference -->
		<script>
		$(document).ready(function() {
			$('#dataTables-example').DataTable({
					responsive: true
			});
		});
		
		</script>
		<script>
		$(document).ready(function() {
			$('#dataTables-example1').DataTable({
					responsive: true
			});
		});
		
		</script>
		<script>
		$(document).ready(function() {
			$('#dataTables-example2').DataTable({
					responsive: true
			});
		});
		
		</script>
		
		<!-- Morris Charts JavaScript -->
		<script src="js/raphael-min.js"></script>
		<script src="js/morris.min.js"></script>
		<script src="js/morris-data.js"></script>
	</div>	
</body>

</html>